## Frist Approch

In [1]:
import pandas as pd
from sklearn.datasets import fetch_openml

# Fetch the Mushroom dataset from UCI repository using scikit-learn
mushroom = fetch_openml(data_id=24, as_frame=True)

# Get features (X) and targets (y)
x = mushroom.data
y = mushroom.target

# Metadata
# print(mushroom.DESCR)

# Variable information
# print(x)


# pd table genrataion
ms = pd.DataFrame(x)
# ms




C:\Users\nayan\AppData\Roaming\Python\Python39\site-packages\sklearn\datasets\_openml.py:1022: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [2]:
numbers = ms.nunique().values
result = 1  # Initialize the result to 1
for num in numbers:
    result *= num  # Multiply each number with the result

print(result)

97519848652800


## Data import

In [3]:
# cap-shape:                bell=b,conical=c,convex=x,flat=f, knobbed=k,sunken=s
# cap-surface:              fibrous=f,grooves=g,scaly=y,smooth=s
# cap-color:                brown=n,buff=b,cinnamon=c,gray=g,green=r, pink=p,purple=u,red=e,white=w,yellow=y
# bruises?:                 bruises=t,no=f
# odor:                     almond=a,anise=l,creosote=c,fishy=y,foul=f, musty=m,none=n,pungent=p,spicy=s
# gill-attachment:          attached=a,descending=d,free=f,notched=n
# gill-spacing:             close=c,crowded=w,distant=d
# gill-size:                broad=b,narrow=n
# gill-color:               black=k,brown=n,buff=b,chocolate=h,gray=g, green=r,orange=o,pink=p,purple=u,red=e, white=w,yellow=y
# stalk-shape:              enlarging=e,tapering=t
# stalk-root:               bulbous=b,club=c,cup=u,equal=e, rhizomorphs=z,rooted=r,missing=?
# stalk-surface-above-ring: fibrous=f,scaly=y,silky=k,smooth=s
# stalk-surface-below-ring: fibrous=f,scaly=y,silky=k,smooth=s
# stalk-color-above-ring:   brown=n,buff=b,cinnamon=c,gray=g,orange=o, pink=p,red=e,white=w,yellow=y
# stalk-color-below-ring:   brown=n,buff=b,cinnamon=c,gray=g,orange=o, pink=p,red=e,white=w,yellow=y
# veil-type:                partial=p,universal=u
# veil-color:               brown=n,orange=o,white=w,yellow=y
# ring-number:              none=n,one=o,two=t
# ring-type:                cobwebby=c,evanescent=e,flaring=f,large=l, none=n,pendant=p,sheathing=s,zone=z
# spore-print-color:        black=k,brown=n,buff=b,chocolate=h,green=r, orange=o,purple=u,white=w,yellow=y
# population:               abundant=a,clustered=c,numerous=n, scattered=s,several=v,solitary=y
# habitat:                  grasses=g,leaves=l,meadows=m,paths=p, urban=u,waste=w,woods=d

In [4]:
import pandas as pd

# Specify the path to the agaricus-lepiota.data file
file_path = "D:/Data project/DATA science/Github/Machine-Learning-Repository/Mushroom dataset/mushroom metadata/agaricus-lepiota.data" # Replace with the actual file path

# Define column names based on the dataset's attributes
column_names = [
    "class",
    "cap-shape",
    "cap-surface",
    "cap-color",
    "bruises",
    "odor",
    "gill-attachment",
    "gill-spacing",
    "gill-size",
    "gill-color",
    "stalk-shape",
    "stalk-root",
    "stalk-surface-above-ring",
    "stalk-surface-below-ring",
    "stalk-color-above-ring",
    "stalk-color-below-ring",
    "veil-type",
    "veil-color",
    "ring-number",
    "ring-type",
    "spore-print-color",
    "population",
    "habitat"
]

# Read the data file into a Pandas DataFrame
df = pd.read_csv(file_path, names=column_names)

# Display the DataFrame
print(df.shape)
df.head()



(8124, 23)


class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0     p         x           s         n       t    p               f   
1     e         x           s         y       t    a               f   
2     e         b           s         w       t    l               f   
3     p         x           y         w       t    p               f   
4     e         x           s         g       f    n               f   

  gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0            c         n          k  ...                        s   
1            c         b          k  ...                        s   
2            c         b          n  ...                        s   
3            c         n          n  ...                        s   
4            w         b          k  ...                        s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

In [5]:

# Show df descriptive statistics
df.describe()

class cap-shape cap-surface cap-color bruises  odor gill-attachment  \
count   8124      8124        8124      8124    8124  8124            8124   
unique     2         6           4        10       2     9               2   
top        e         x           y         n       f     n               f   
freq    4208      3656        3244      2284    4748  3528            7914   

       gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
count          8124      8124       8124  ...                     8124   
unique            2         2         12  ...                        4   
top               c         b          b  ...                        s   
freq           6812      5612       1728  ...                     4936   

       stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
count                    8124                   8124      8124       8124   
unique                      9                      9         1          4   
top                         w                      w         p          w   
freq                     4464                   4384      8124       7924   

       ring-number ring-type spore-print-color population habitat  
count         8124      8124              8124       8124    8124  
unique           3         5                 9          6       7  
top              o         p                 w          v       d  
freq          7488      3968              2388       4040    3148  

[4 rows x 23 columns]

In [6]:
# Display df info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   class                     8124 non-null   object
 1   cap-shape                 8124 non-null   object
 2   cap-surface               8124 non-null   object
 3   cap-color                 8124 non-null   object
 4   bruises                   8124 non-null   object
 5   odor                      8124 non-null   object
 6   gill-attachment           8124 non-null   object
 7   gill-spacing              8124 non-null   object
 8   gill-size                 8124 non-null   object
 9   gill-color                8124 non-null   object
 10  stalk-shape               8124 non-null   object
 11  stalk-root                8124 non-null   object
 12  stalk-surface-above-ring  8124 non-null   object
 13  stalk-surface-below-ring  8124 non-null   object
 14  stalk-color-above-ring  

In [7]:
# Sum null values
df.isna().sum()

class                       0
cap-shape                   0
cap-surface                 0
cap-color                   0
bruises                     0
odor                        0
gill-attachment             0
gill-spacing                0
gill-size                   0
gill-color                  0
stalk-shape                 0
stalk-root                  0
stalk-surface-above-ring    0
stalk-surface-below-ring    0
stalk-color-above-ring      0
stalk-color-below-ring      0
veil-type                   0
veil-color                  0
ring-number                 0
ring-type                   0
spore-print-color           0
population                  0
habitat                     0
dtype: int64

### check the case

In [8]:
numbers = df.nunique().values
result = 1  # Initialize the result to 1
for num in numbers:
    result *= num  # Multiply each number with the result

print(result)

243799621632000


## chenge the class to binory

In [9]:
# Convert "class" to binary

df['class'] = (df['class'] == 'p').astype(int)

## One Hot encoding

In [10]:
df_ohe = pd.get_dummies(df)
print(df_ohe.shape)
df_ohe

(8124, 118)


class  cap-shape_b  cap-shape_c  cap-shape_f  cap-shape_k  cap-shape_s  \
0         1            0            0            0            0            0   
1         0            0            0            0            0            0   
2         0            1            0            0            0            0   
3         1            0            0            0            0            0   
4         0            0            0            0            0            0   
...     ...          ...          ...          ...          ...          ...   
8119      0            0            0            0            1            0   
8120      0            0            0            0            0            0   
8121      0            0            0            1            0            0   
8122      1            0            0            0            1            0   
8123      0            0            0            0            0            0   

      cap-shape_x  cap-surface_f  cap-surface_g  cap-surface_s  ...  \
0               1              0              0              1  ...   
1               1              0              0              1  ...   
2               0              0              0              1  ...   
3               1              0              0              0  ...   
4               1              0              0              1  ...   
...           ...            ...            ...            ...  ...   
8119            0              0              0              1  ...   
8120            1              0              0              1  ...   
8121            0              0              0              1  ...   
8122            0              0              0              0  ...   
8123            1              0              0              1  ...   

      population_s  population_v  population_y  habitat_d  habitat_g  \
0                1             0             0          0          0   
1                0             0             0          0          1   
2                0             0             0          0          0   
3                1             0             0          0          0   
4                0             0             0          0          1   
...            ...           ...           ...        ...        ...   
8119             0             0             0          0          0   
8120             0             1             0          0          0   
8121             0             0             0          0          0   
8122             0             1             0          0          0   
8123             0             0             0          0          0   

      habitat_l  habitat_m  habitat_p  habitat_u  habitat_w  
0             0          0          0          1          0  
1             0          0          0          0          0  
2             0          1          0          0          0  
3             0          0          0          1          0  
4             0          0          0          0          0  
...         ...        ...        ...        ...        ...  
8119          1          0          0          0          0  
8120          1          0          0          0          0  
8121          1          0          0          0          0  
8122          1          0          0          0          0  
8123          1          0          0          0          0  

[8124 rows x 118 columns]

## Separate X and y from df

In [11]:
X, y = df_ohe.iloc[:, 1:].values, df_ohe.iloc[:, 0].values

## Perform the actual data splitting

In [12]:

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size = 0.3,
                                                    random_state = 0,
                                                    stratify = y)

In [13]:
X_train, X_test, y_train, y_test

(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 1, ..., 0, 0, 0],
        ...,
        [0, 0, 1, ..., 1, 0, 0],
        [0, 0, 1, ..., 1, 0, 0],
        [0, 0, 0, ..., 1, 0, 0]], dtype=uint8),
 array([[0, 0, 1, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 1, 0, 0],
        [0, 0, 1, ..., 0, 0, 0]], dtype=uint8),
 array([0, 0, 0, ..., 1, 1, 1]),
 array([0, 0, 1, ..., 1, 1, 1]))

# Bringing features onto the same scale

## Min-Max Normalization

In [14]:
from sklearn.preprocessing import MinMaxScaler

mms = MinMaxScaler()

X_train_norm = mms.fit_transform(X_train)
X_test_norm = mms.transform(X_test)

In [15]:
X_train_norm

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 1., 0., 0.],
       [0., 0., 1., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.]])

In [16]:
X_test_norm

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]])

In [17]:
pd.DataFrame(X_train_norm).describe()

0            1            2            3            4    \
count  5686.000000  5686.000000  5686.000000  5686.000000  5686.000000   
mean      0.060324     0.000528     0.389202     0.100950     0.003869   
std       0.238106     0.022966     0.487612     0.301289     0.062088   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       0.000000     0.000000     1.000000     0.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

               5            6            7            8            9    ...  \
count  5686.000000  5686.000000  5686.000000  5686.000000  5686.000000  ...   
mean      0.445128     0.282448     0.000528     0.312874     0.404151  ...   
std       0.497024     0.450230     0.022966     0.463704     0.490770  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%       1.000000     1.000000     0.000000     1.000000     1.000000  ...   
max       1.000000     1.000000     1.000000     1.000000     1.000000  ...   

               107          108          109          110          111  \
count  5686.000000  5686.000000  5686.000000  5686.000000  5686.000000   
mean      0.157756     0.495955     0.210517     0.380760     0.266796   
std       0.364544     0.500028     0.407712     0.485616     0.442324   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       0.000000     1.000000     0.000000     1.000000     1.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

               112          113          114          115          116  
count  5686.000000  5686.000000  5686.000000  5686.000000  5686.000000  
mean      0.103764     0.037460     0.142279     0.046254     0.022687  
std       0.304980     0.189904     0.349367     0.210053     0.148918  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000     0.000000     0.000000  
75%       0.000000     0.000000     0.000000     0.000000     0.000000  
max       1.000000     1.000000     1.000000     1.000000     1.000000  

[8 rows x 117 columns]

## Standardization

In [18]:
from sklearn.preprocessing import StandardScaler

stdsc = StandardScaler()
X_train_std = stdsc.fit_transform(X_train)
X_test_std = stdsc.transform(X_test)

In [19]:

pd.DataFrame(X_train_std).describe()

0             1             2             3             4    \
count  5.686000e+03  5.686000e+03  5.686000e+03  5.686000e+03  5.686000e+03   
mean   3.374016e-17 -2.499271e-18 -9.184821e-17  4.998542e-18  6.560586e-18   
std    1.000088e+00  1.000088e+00  1.000088e+00  1.000088e+00  1.000088e+00   
min   -2.533696e-01 -2.297586e-02 -7.982489e-01 -3.350893e-01 -6.232320e-02   
25%   -2.533696e-01 -2.297586e-02 -7.982489e-01 -3.350893e-01 -6.232320e-02   
50%   -2.533696e-01 -2.297586e-02 -7.982489e-01 -3.350893e-01 -6.232320e-02   
75%   -2.533696e-01 -2.297586e-02  1.252742e+00 -3.350893e-01 -6.232320e-02   
max    3.946804e+00  4.352394e+01  1.252742e+00  2.984279e+00  1.604539e+01   

                5             6             7             8             9    \
count  5.686000e+03  5.686000e+03  5.686000e+03  5.686000e+03  5.686000e+03   
mean   2.499271e-17  1.187154e-16 -1.187154e-17  5.685841e-17  1.874453e-17   
std    1.000088e+00  1.000088e+00  1.000088e+00  1.000088e+00  1.000088e+00   
min   -8.956666e-01 -6.273974e-01 -2.297586e-02 -6.747863e-01 -8.235753e-01   
25%   -8.956666e-01 -6.273974e-01 -2.297586e-02 -6.747863e-01 -8.235753e-01   
50%   -8.956666e-01 -6.273974e-01 -2.297586e-02 -6.747863e-01 -8.235753e-01   
75%    1.116487e+00  1.593886e+00 -2.297586e-02  1.481951e+00  1.214218e+00   
max    1.116487e+00  1.593886e+00  4.352394e+01  1.481951e+00  1.214218e+00   

       ...           107           108           109           110  \
count  ...  5.686000e+03  5.686000e+03  5.686000e+03  5.686000e+03   
mean   ... -2.249344e-17  7.997667e-17  1.999417e-17  6.498105e-17   
std    ...  1.000088e+00  1.000088e+00  1.000088e+00  1.000088e+00   
min    ... -4.327866e-01 -9.919424e-01 -5.163834e-01 -7.841442e-01   
25%    ... -4.327866e-01 -9.919424e-01 -5.163834e-01 -7.841442e-01   
50%    ... -4.327866e-01 -9.919424e-01 -5.163834e-01 -7.841442e-01   
75%    ... -4.327866e-01  1.008123e+00 -5.163834e-01  1.275276e+00   
max    ...  2.310608e+00  1.008123e+00  1.936546e+00  1.275276e+00   

                111           112           113           114           115  \
count  5.686000e+03  5.686000e+03  5.686000e+03  5.686000e+03  5.686000e+03   
mean  -1.262132e-16 -1.811971e-17  1.874453e-17  6.498105e-17  8.997375e-17   
std    1.000088e+00  1.000088e+00  1.000088e+00  1.000088e+00  1.000088e+00   
min   -6.032215e-01 -3.402603e-01 -1.972773e-01 -4.072845e-01 -2.202207e-01   
25%   -6.032215e-01 -3.402603e-01 -1.972773e-01 -4.072845e-01 -2.202207e-01   
50%   -6.032215e-01 -3.402603e-01 -1.972773e-01 -4.072845e-01 -2.202207e-01   
75%    1.657766e+00 -3.402603e-01 -1.972773e-01 -4.072845e-01 -2.202207e-01   
max    1.657766e+00  2.938926e+00  5.069007e+00  2.455286e+00  4.540900e+00   

                116  
count  5.686000e+03  
mean  -1.749490e-17  
std    1.000088e+00  
min   -1.523613e-01  
25%   -1.523613e-01  
50%   -1.523613e-01  
75%   -1.523613e-01  
max    6.563347e+00  

[8 rows x 117 columns]

## Sequential feature selection algorithm

In [20]:
from sklearn.base import clone
from itertools import combinations
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split


class SBS:
    def __init__(self, estimator, k_features, scoring=accuracy_score,
                 test_size=0.25, random_state=1):
        self.scoring = scoring
        self.estimator = clone(estimator)
        self.k_features = k_features
        self.test_size = test_size
        self.random_state = random_state

    def fit(self, X, y):
        
        X_train, X_test, y_train, y_test = \
            train_test_split(X, y, test_size=self.test_size,
                             random_state=self.random_state)

        dim = X_train.shape[1]
        self.indices_ = tuple(range(dim))
        self.subsets_ = [self.indices_]
        score = self._calc_score(X_train, y_train, 
                                 X_test, y_test, self.indices_)
        self.scores_ = [score]

        while dim > self.k_features:
            scores = []
            subsets = []

            for p in combinations(self.indices_, r=dim - 1):
                score = self._calc_score(X_train, y_train, 
                                         X_test, y_test, p)
                scores.append(score)
                subsets.append(p)

            best = np.argmax(scores)
            self.indices_ = subsets[best]
            self.subsets_.append(self.indices_)
            dim -= 1

            self.scores_.append(scores[best])
        self.k_score_ = self.scores_[-1]

        return self

    def transform(self, X):
        return X[:, self.indices_]

    def _calc_score(self, X_train, y_train, X_test, y_test, indices):
        self.estimator.fit(X_train[:, indices], y_train)
        y_pred = self.estimator.predict(X_test[:, indices])
        score = self.scoring(y_test, y_pred)
        return score

### Apply the SBS feature selection

In [27]:

import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)

# selecting features
sbs = SBS(knn, k_features=1)
sbs.fit(X_train_std, y_train)

# plotting performance of feature subsets
k_feat = [len(k) for k in sbs.subsets_]

plt.plot(k_feat, sbs.scores_, marker='o')
plt.ylim([0.7, 1.02])
plt.ylabel('Accuracy')
plt.xlabel('Number of features')
plt.grid()
plt.tight_layout()
# plt.savefig('figures/04_09.png', dpi=300)
plt.show()

AttributeError: 'NoneType' object has no attribute 'split'