In [1]:
import pandas as pd

# Specify the path to the agaricus-lepiota.data file
file_path = "D:/Data project/DATA science/Github/Machine-Learning-Repository/Mushroom dataset/mushroom metadata/agaricus-lepiota.data" # Replace with the actual file path

# Define column names based on the dataset's attributes
column_names = [
    "class",
    "cap-shape",
    "cap-surface",
    "cap-color",
    "bruises",
    "odor",
    "gill-attachment",
    "gill-spacing",
    "gill-size",
    "gill-color",
    "stalk-shape",
    "stalk-root",
    "stalk-surface-above-ring",
    "stalk-surface-below-ring",
    "stalk-color-above-ring",
    "stalk-color-below-ring",
    "veil-type",
    "veil-color",
    "ring-number",
    "ring-type",
    "spore-print-color",
    "population",
    "habitat"
]

# Read the data file into a Pandas DataFrame
df = pd.read_csv(file_path, names=column_names)

# Display the DataFrame
print(df.shape)
df.head()



(8124, 23)


class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0     p         x           s         n       t    p               f   
1     e         x           s         y       t    a               f   
2     e         b           s         w       t    l               f   
3     p         x           y         w       t    p               f   
4     e         x           s         g       f    n               f   

  gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0            c         n          k  ...                        s   
1            c         b          k  ...                        s   
2            c         b          n  ...                        s   
3            c         n          n  ...                        s   
4            w         b          k  ...                        s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

In [2]:
# Convert "class" to binary

df['class'] = (df['class'] == 'p').astype(int)

# One hot Encoder
df_ohe = pd.get_dummies(df)
print(df_ohe.shape)
df_ohe

(8124, 118)


class  cap-shape_b  cap-shape_c  cap-shape_f  cap-shape_k  cap-shape_s  \
0         1            0            0            0            0            0   
1         0            0            0            0            0            0   
2         0            1            0            0            0            0   
3         1            0            0            0            0            0   
4         0            0            0            0            0            0   
...     ...          ...          ...          ...          ...          ...   
8119      0            0            0            0            1            0   
8120      0            0            0            0            0            0   
8121      0            0            0            1            0            0   
8122      1            0            0            0            1            0   
8123      0            0            0            0            0            0   

      cap-shape_x  cap-surface_f  cap-surface_g  cap-surface_s  ...  \
0               1              0              0              1  ...   
1               1              0              0              1  ...   
2               0              0              0              1  ...   
3               1              0              0              0  ...   
4               1              0              0              1  ...   
...           ...            ...            ...            ...  ...   
8119            0              0              0              1  ...   
8120            1              0              0              1  ...   
8121            0              0              0              1  ...   
8122            0              0              0              0  ...   
8123            1              0              0              1  ...   

      population_s  population_v  population_y  habitat_d  habitat_g  \
0                1             0             0          0          0   
1                0             0             0          0          1   
2                0             0             0          0          0   
3                1             0             0          0          0   
4                0             0             0          0          1   
...            ...           ...           ...        ...        ...   
8119             0             0             0          0          0   
8120             0             1             0          0          0   
8121             0             0             0          0          0   
8122             0             1             0          0          0   
8123             0             0             0          0          0   

      habitat_l  habitat_m  habitat_p  habitat_u  habitat_w  
0             0          0          0          1          0  
1             0          0          0          0          0  
2             0          1          0          0          0  
3             0          0          0          1          0  
4             0          0          0          0          0  
...         ...        ...        ...        ...        ...  
8119          1          0          0          0          0  
8120          1          0          0          0          0  
8121          1          0          0          0          0  
8122          1          0          0          0          0  
8123          1          0          0          0          0  

[8124 rows x 118 columns]

# Basic ML test

In [3]:
df_ohe.iloc[8123,1:].values

array([0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0], dtype=int32)

In [21]:
from sklearn.tree import DecisionTreeClassifier

X_basic = df_ohe.drop(columns=['class'])
Y_basic = df_ohe['class']
model = DecisionTreeClassifier()
model.fit(X_basic,Y_basic)
predictions = model.predict([[0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0],
                             [0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0]])
predictions

c:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([0, 0])

## Model Validation

In [147]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

X_basic = df_ohe.drop(columns=['class'])
Y_basic = df_ohe['class']

X_train,X_test, y_train, y_test = train_test_split(X_basic,Y_basic,test_size=0.2)
model = DecisionTreeClassifier()
model.fit(X_train,y_train)
predictions = model.predict(X_test)

score = accuracy_score(y_test,predictions)
score

1.0

## Persisting Models

In [17]:
from sklearn.tree import DecisionTreeClassifier
import joblib

X_basic = df_ohe.drop(columns=['class'])
Y_basic = df_ohe['class']
model = DecisionTreeClassifier()
model.fit(X_basic,Y_basic)
joblib.dump(model,'D:/Data project/DATA science/Github/Machine-Learning-Repository/Mushroom dataset/Poison_recommender.joblib')
predictions = model.predict([[0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0]])
predictions

C:\Users\nayan\AppData\Roaming\Python\Python39\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([0])

## Visualizing a Decision Tree

In [52]:
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree

X_basic = df_ohe.drop(columns=['class'])
Y_basic = df_ohe['class']
model = DecisionTreeClassifier()
model.fit(X_basic,Y_basic)


feature_names_ = list(df_ohe.columns[1:])
tree.export_graphviz(model,out_file='D:/Data project/DATA science/Github/Machine-Learning-Repository/Mushroom dataset/music-recommender.dot',
                     feature_names=feature_names_,
                     class_names=sorted(set(Y_basic)),
                     label='all',
                     rounded=True,
                     filled=True
                     )

TypeError: can only concatenate str (not "numpy.int32") to str

In [55]:
from sklearn.tree import DecisionTreeClassifier, export_graphviz

X_basic = df_ohe.drop(columns=['class'])
Y_basic = df_ohe['class']
model = DecisionTreeClassifier()
model.fit(X_basic, Y_basic)

feature_names_ = list(df_ohe.columns[1:])
class_names_ = sorted(set(Y_basic))

export_graphviz(model, out_file='D:/Data project/DATA science/Github/Machine-Learning-Repository/Mushroom dataset/music-recommender.dot',
                feature_names=feature_names_,
                class_names=class_names_,
                label='all',
                rounded=True,
                filled=True
                )



TypeError: can only concatenate str (not "numpy.int32") to str