## Frist Approch

In [2]:
import pandas as pd
from sklearn.datasets import fetch_openml

# Fetch the Mushroom dataset from UCI repository using scikit-learn
mushroom = fetch_openml(data_id=24, as_frame=True)

# Get features (X) and targets (y)
x = mushroom.data
y = mushroom.target

# Metadata
# print(mushroom.DESCR)

# Variable information
# print(x)


# pd table genrataion
ms = pd.DataFrame(x)
# ms




In [ ]:
numbers = ms.nunique().values
result = 1  # Initialize the result to 1
for num in numbers:
    result *= num  # Multiply each number with the result

print(result)

## Data import

In [ ]:
# cap-shape:                bell=b,conical=c,convex=x,flat=f, knobbed=k,sunken=s
# cap-surface:              fibrous=f,grooves=g,scaly=y,smooth=s
# cap-color:                brown=n,buff=b,cinnamon=c,gray=g,green=r, pink=p,purple=u,red=e,white=w,yellow=y
# bruises?:                 bruises=t,no=f
# odor:                     almond=a,anise=l,creosote=c,fishy=y,foul=f, musty=m,none=n,pungent=p,spicy=s
# gill-attachment:          attached=a,descending=d,free=f,notched=n
# gill-spacing:             close=c,crowded=w,distant=d
# gill-size:                broad=b,narrow=n
# gill-color:               black=k,brown=n,buff=b,chocolate=h,gray=g, green=r,orange=o,pink=p,purple=u,red=e, white=w,yellow=y
# stalk-shape:              enlarging=e,tapering=t
# stalk-root:               bulbous=b,club=c,cup=u,equal=e, rhizomorphs=z,rooted=r,missing=?
# stalk-surface-above-ring: fibrous=f,scaly=y,silky=k,smooth=s
# stalk-surface-below-ring: fibrous=f,scaly=y,silky=k,smooth=s
# stalk-color-above-ring:   brown=n,buff=b,cinnamon=c,gray=g,orange=o, pink=p,red=e,white=w,yellow=y
# stalk-color-below-ring:   brown=n,buff=b,cinnamon=c,gray=g,orange=o, pink=p,red=e,white=w,yellow=y
# veil-type:                partial=p,universal=u
# veil-color:               brown=n,orange=o,white=w,yellow=y
# ring-number:              none=n,one=o,two=t
# ring-type:                cobwebby=c,evanescent=e,flaring=f,large=l, none=n,pendant=p,sheathing=s,zone=z
# spore-print-color:        black=k,brown=n,buff=b,chocolate=h,green=r, orange=o,purple=u,white=w,yellow=y
# population:               abundant=a,clustered=c,numerous=n, scattered=s,several=v,solitary=y
# habitat:                  grasses=g,leaves=l,meadows=m,paths=p, urban=u,waste=w,woods=d

In [1]:
import pandas as pd

# Specify the path to the agaricus-lepiota.data file
file_path = "D:/Data project/DATA science/Github/UC-Irvine-Machine-Learning-Repository-Mushroom/mushroom metadata/agaricus-lepiota.data" # Replace with the actual file path

# Define column names based on the dataset's attributes
column_names = [
    "class",
    "cap-shape",
    "cap-surface",
    "cap-color",
    "bruises",
    "odor",
    "gill-attachment",
    "gill-spacing",
    "gill-size",
    "gill-color",
    "stalk-shape",
    "stalk-root",
    "stalk-surface-above-ring",
    "stalk-surface-below-ring",
    "stalk-color-above-ring",
    "stalk-color-below-ring",
    "veil-type",
    "veil-color",
    "ring-number",
    "ring-type",
    "spore-print-color",
    "population",
    "habitat"
]

# Read the data file into a Pandas DataFrame
df = pd.read_csv(file_path, names=column_names)

# Display the DataFrame
df


class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0        p         x           s         n       t    p               f   
1        e         x           s         y       t    a               f   
2        e         b           s         w       t    l               f   
3        p         x           y         w       t    p               f   
4        e         x           s         g       f    n               f   
...    ...       ...         ...       ...     ...  ...             ...   
8119     e         k           s         n       f    n               a   
8120     e         x           s         n       f    n               a   
8121     e         f           s         n       f    n               a   
8122     p         k           y         n       f    y               f   
8123     e         x           s         n       f    n               a   

     gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0               c         n          k  ...                        s   
1               c         b          k  ...                        s   
2               c         b          n  ...                        s   
3               c         n          n  ...                        s   
4               w         b          k  ...                        s   
...           ...       ...        ...  ...                      ...   
8119            c         b          y  ...                        s   
8120            c         b          y  ...                        s   
8121            c         b          n  ...                        s   
8122            c         n          b  ...                        k   
8123            c         b          y  ...                        s   

     stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                         w                      w         p          w   
1                         w                      w         p          w   
2                         w                      w         p          w   
3                         w                      w         p          w   
4                         w                      w         p          w   
...                     ...                    ...       ...        ...   
8119                      o                      o         p          o   
8120                      o                      o         p          n   
8121                      o                      o         p          o   
8122                      w                      w         p          w   
8123                      o                      o         p          o   

     ring-number ring-type spore-print-color population habitat  
0              o         p                 k          s       u  
1              o         p                 n          n       g  
2              o         p                 n          n       m  
3              o         p                 k          s       u  
4              o         e                 n          a       g  
...          ...       ...               ...        ...     ...  
8119           o         p                 b          c       l  
8120           o         p                 b          v       l  
8121           o         p                 b          c       l  
8122           o         e                 w          v       l  
8123           o         p                 o          c       l  

[8124 rows x 23 columns]

### check the case

In [ ]:
numbers = df.nunique().values
result = 1  # Initialize the result to 1
for num in numbers:
    result *= num  # Multiply each number with the result

print(result)

## chenge the class to binory

In [4]:
# Convert "class" to binary

df['class'] = (df['class'] == 'p').astype(int)

## One Hot encoding

In [5]:
df_ohe = pd.get_dummies(df)
df_ohe.shape

(8124, 118)

## Separate X and y from df

In [6]:
X, y = df_ohe.iloc[:, 1:].values, df_ohe.iloc[:, 0].values

## Perform the actual data splitting

In [7]:

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size = 0.3,
                                                    random_state = 0,
                                                    stratify = y)

In [8]:
X_train, X_test, y_train, y_test

(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 1, ..., 1, 0, 0],
        [0, 0, 1, ..., 1, 0, 0],
        [0, 0, 1, ..., 0, 1, 0]], dtype=uint8),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 1, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 1],
        [0, 0, 1, ..., 0, 0, 0],
        [0, 0, 1, ..., 0, 0, 0]], dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]))

# Bringing features onto the same scale

## Min-Max Normalization

In [9]:
from sklearn.preprocessing import MinMaxScaler

mms = MinMaxScaler()

X_train_norm = mms.fit_transform(X_train)
X_test_norm = mms.transform(X_test)

In [10]:
X_train_norm

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 1., 0., 0.],
       [0., 0., 1., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 1., 0.]])

In [11]:
X_test_norm

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]])

In [12]:
pd.DataFrame(X_train_norm).describe()

0            1            2            3            4    \
count  5686.000000  5686.000000  5686.000000  5686.000000  5686.000000   
mean      0.055223     0.000703     0.388850     0.101829     0.003166   
std       0.228436     0.026516     0.487532     0.302450     0.056180   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       0.000000     0.000000     1.000000     0.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

               5            6            7            8            9    ...  \
count  5686.000000  5686.000000  5686.000000  5686.000000  5686.000000  ...   
mean      0.450229     0.283152     0.000528     0.312698     0.403623  ...   
std       0.497560     0.450569     0.022966     0.463633     0.490667  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%       1.000000     1.000000     0.000000     1.000000     1.000000  ...   
max       1.000000     1.000000     1.000000     1.000000     1.000000  ...   

               107          108          109          110          111  \
count  5686.000000  5686.000000  5686.000000  5686.000000  5686.000000   
mean      0.151249     0.497010     0.211924     0.387091     0.262926   
std       0.358323     0.500035     0.408707     0.487128     0.440262   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       0.000000     1.000000     0.000000     1.000000     1.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

               112          113          114          115          116  
count  5686.000000  5686.000000  5686.000000  5686.000000  5686.000000  
mean      0.100950     0.038516     0.142983     0.043616     0.023918  
std       0.301289     0.192454     0.350086     0.204257     0.152808  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000     0.000000     0.000000  
75%       0.000000     0.000000     0.000000     0.000000     0.000000  
max       1.000000     1.000000     1.000000     1.000000     1.000000  

[8 rows x 117 columns]

## Standardization

In [13]:
from sklearn.preprocessing import StandardScaler

stdsc = StandardScaler()
X_train_std = stdsc.fit_transform(X_train)
X_test_std = stdsc.transform(X_test)

In [14]:

pd.DataFrame(X_train_std).describe()

0             1             2             3             4    \
count  5.686000e+03  5.686000e+03  5.686000e+03  5.686000e+03  5.686000e+03   
mean   3.686425e-17  4.373724e-18 -1.149665e-16 -1.249635e-18 -1.749490e-17   
std    1.000088e+00  1.000088e+00  1.000088e+00  1.000088e+00  1.000088e+00   
min   -2.417669e-01 -2.653257e-02 -7.976584e-01 -3.367103e-01 -5.635356e-02   
25%   -2.417669e-01 -2.653257e-02 -7.976584e-01 -3.367103e-01 -5.635356e-02   
50%   -2.417669e-01 -2.653257e-02 -7.976584e-01 -3.367103e-01 -5.635356e-02   
75%   -2.417669e-01 -2.653257e-02  1.253669e+00 -3.367103e-01 -5.635356e-02   
max    4.136216e+00  3.768952e+01  1.253669e+00  2.969912e+00  1.774511e+01   

                5             6             7             8            9    \
count  5.686000e+03  5.686000e+03  5.686000e+03  5.686000e+03  5686.000000   
mean  -1.793227e-16 -2.811680e-17 -3.748906e-18  1.499563e-17     0.000000   
std    1.000088e+00  1.000088e+00  1.000088e+00  1.000088e+00     1.000088   
min   -9.049519e-01 -6.284864e-01 -2.297586e-02 -6.745103e-01    -0.822673   
25%   -9.049519e-01 -6.284864e-01 -2.297586e-02 -6.745103e-01    -0.822673   
50%   -9.049519e-01 -6.284864e-01 -2.297586e-02 -6.745103e-01    -0.822673   
75%    1.105031e+00  1.591124e+00 -2.297586e-02  1.482557e+00     1.215549   
max    1.105031e+00  1.591124e+00  4.352394e+01  1.482557e+00     1.215549   

       ...           107           108           109           110  \
count  ...  5.686000e+03  5.686000e+03  5.686000e+03  5.686000e+03   
mean   ...  1.999417e-17  1.424584e-16  8.747448e-18  2.999125e-17   
std    ...  1.000088e+00  1.000088e+00  1.000088e+00  1.000088e+00   
min    ... -4.221391e-01 -9.940382e-01 -5.185684e-01 -7.947099e-01   
25%    ... -4.221391e-01 -9.940382e-01 -5.185684e-01 -7.947099e-01   
50%    ... -4.221391e-01 -9.940382e-01 -5.185684e-01 -7.947099e-01   
75%    ... -4.221391e-01  1.005998e+00 -5.185684e-01  1.258321e+00   
max    ...  2.368887e+00  1.005998e+00  1.928386e+00  1.258321e+00   

                111           112           113           114           115  \
count  5.686000e+03  5.686000e+03  5.686000e+03  5.686000e+03  5.686000e+03   
mean   1.062190e-17  6.248177e-19  7.372849e-17  8.497521e-17 -4.623651e-17   
std    1.000088e+00  1.000088e+00  1.000088e+00  1.000088e+00  1.000088e+00   
min   -5.972577e-01 -3.350893e-01 -2.001463e-01 -4.084577e-01 -2.135533e-01   
25%   -5.972577e-01 -3.350893e-01 -2.001463e-01 -4.084577e-01 -2.135533e-01   
50%   -5.972577e-01 -3.350893e-01 -2.001463e-01 -4.084577e-01 -2.135533e-01   
75%    1.674319e+00 -3.350893e-01 -2.001463e-01 -4.084577e-01 -2.135533e-01   
max    1.674319e+00  2.984279e+00  4.996346e+00  2.448234e+00  4.682672e+00   

                116  
count  5.686000e+03  
mean   1.624526e-17  
std    1.000088e+00  
min   -1.565391e-01  
25%   -1.565391e-01  
50%   -1.565391e-01  
75%   -1.565391e-01  
max    6.388178e+00  

[8 rows x 117 columns]

## Sequential feature selection algorithm

In [15]:
from sklearn.base import clone
from itertools import combinations
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split


class SBS:
    def __init__(self, estimator, k_features, scoring=accuracy_score,
                 test_size=0.25, random_state=1):
        self.scoring = scoring
        self.estimator = clone(estimator)
        self.k_features = k_features
        self.test_size = test_size
        self.random_state = random_state

    def fit(self, X, y):
        
        X_train, X_test, y_train, y_test = \
            train_test_split(X, y, test_size=self.test_size,
                             random_state=self.random_state)

        dim = X_train.shape[1]
        self.indices_ = tuple(range(dim))
        self.subsets_ = [self.indices_]
        score = self._calc_score(X_train, y_train, 
                                 X_test, y_test, self.indices_)
        self.scores_ = [score]

        while dim > self.k_features:
            scores = []
            subsets = []

            for p in combinations(self.indices_, r=dim - 1):
                score = self._calc_score(X_train, y_train, 
                                         X_test, y_test, p)
                scores.append(score)
                subsets.append(p)

            best = np.argmax(scores)
            self.indices_ = subsets[best]
            self.subsets_.append(self.indices_)
            dim -= 1

            self.scores_.append(scores[best])
        self.k_score_ = self.scores_[-1]

        return self

    def transform(self, X):
        return X[:, self.indices_]

    def _calc_score(self, X_train, y_train, X_test, y_test, indices):
        self.estimator.fit(X_train[:, indices], y_train)
        y_pred = self.estimator.predict(X_test[:, indices])
        score = self.scoring(y_test, y_pred)
        return score

### Apply the SBS feature selection

In [ ]:

import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)

# selecting features
sbs = SBS(knn, k_features=1)
sbs.fit(X_train_std, y_train)

# plotting performance of feature subsets
k_feat = [len(k) for k in sbs.subsets_]

plt.plot(k_feat, sbs.scores_, marker='o')
plt.ylim([0.7, 1.02])
plt.ylabel('Accuracy')
plt.xlabel('Number of features')
plt.grid()
plt.tight_layout()
# plt.savefig('figures/04_09.png', dpi=300)
plt.show()

In [20]:
df_ohe.iloc[:,2:]

cap-shape_c  cap-shape_f  cap-shape_k  cap-shape_s  cap-shape_x  \
0               0            0            0            0            1   
1               0            0            0            0            1   
2               0            0            0            0            0   
3               0            0            0            0            1   
4               0            0            0            0            1   
...           ...          ...          ...          ...          ...   
8119            0            0            1            0            0   
8120            0            0            0            0            1   
8121            0            1            0            0            0   
8122            0            0            1            0            0   
8123            0            0            0            0            1   

      cap-surface_f  cap-surface_g  cap-surface_s  cap-surface_y  cap-color_b  \
0                 0              0              1              0            0   
1                 0              0              1              0            0   
2                 0              0              1              0            0   
3                 0              0              0              1            0   
4                 0              0              1              0            0   
...             ...            ...            ...            ...          ...   
8119              0              0              1              0            0   
8120              0              0              1              0            0   
8121              0              0              1              0            0   
8122              0              0              0              1            0   
8123              0              0              1              0            0   

      ...  population_s  population_v  population_y  habitat_d  habitat_g  \
0     ...             1             0             0          0          0   
1     ...             0             0             0          0          1   
2     ...             0             0             0          0          0   
3     ...             1             0             0          0          0   
4     ...             0             0             0          0          1   
...   ...           ...           ...           ...        ...        ...   
8119  ...             0             0             0          0          0   
8120  ...             0             1             0          0          0   
8121  ...             0             0             0          0          0   
8122  ...             0             1             0          0          0   
8123  ...             0             0             0          0          0   

      habitat_l  habitat_m  habitat_p  habitat_u  habitat_w  
0             0          0          0          1          0  
1             0          0          0          0          0  
2             0          1          0          0          0  
3             0          0          0          1          0  
4             0          0          0          0          0  
...         ...        ...        ...        ...        ...  
8119          1          0          0          0          0  
8120          1          0          0          0          0  
8121          1          0          0          0          0  
8122          1          0          0          0          0  
8123          1          0          0          0          0  

[8124 rows x 116 columns]